# ==================
# Environment
# ==================
environment: production

# ==================
# Base
# ==================
title: Nic Chan – Hong Kong Web Developer
description: The personal website and portfolio of Hong Kong based Web Developer Nic Chan.
url: https://www.nicchan.me
exclude:
  - "node_modules"
  - "package.json"
  - "gulpfile.js"
  - "Gemfile"
  - "Gemfile.lock"

plugins:
  - jekyll-feed

collections:
  projects:
    output: true
  archived:
    output: true
  posts:
    output: true
    permalink: /blog/:title/

imgurl: /img/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "projects"
    values:
      layout: "projects"
      body: "projects"
  - scope:
      type: "archived"
    values:
      layout: "projects"
      body: "projects"
      hidden: true

webmentions:
  username: www.nicchan.me
  cache_folder: .jekyll-cache
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: monthly
