# ==================
# Environment
# ==================
environment: development

# ==================
# Base
# ==================
title: Nic Chan – Hong Kong Web Developer
description: The personal website and portfolio of Hong Kong based Web Developer Nic Chan.
safe: true
exclude:
  - "node_modules"
  - "package.json"
  - "gulpfile.js"
  - "Gemfile"
  - "Gemfile.lock"


collections:
  projects:
    output: true
  archived:
    output: true
  posts:
    output: true
    permalink: /blog/:title/


imgurl: /img/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "projects"
    values:
      layout: "projects"
      body: "projects"
  -
    scope:
      type: "archived"
    values:
      layout: "projects"
      body: "projects"
