# ==================
# Environment
# ==================
environment: development

# ==================
# Base
# ==================
title: Nic Chan – Hong Kong Web Developer
description: > #
    The personal website and portfolio of Hong Kong based Web Developer Nic Chan.
safe: true
source: https://github.com/nchan0154/nchan0154.github.io
lsi: false
pygments: true
